In [3]:
import numpy as np
from numpy.random import randn

arr1=np.array(randn(3,3,3)*10,dtype=np.int64)
arr2=np.array(randn(3,3,3)*10,dtype=np.int64)

print(arr1)

[[[ -8  -7  -8]
  [-23   8  -9]
  [-21  -5  -2]]

 [[-11  12  14]
  [  6  11  11]
  [  0 -14   2]]

 [[ -6  -3   3]
  [  0   4  -7]
  [  8 -22  -2]]]


In [4]:
print(arr2)

[[[ 18   4   4]
  [-13  15  -7]
  [  0  12   2]]

 [[  3   5  -7]
  [-21  10   3]
  [  5  10  -6]]

 [[ -4   4  -9]
  [-11   0   1]
  [ -6   3   4]]]


In [5]:
print(arr1+100)

[[[ 92  93  92]
  [ 77 108  91]
  [ 79  95  98]]

 [[ 89 112 114]
  [106 111 111]
  [100  86 102]]

 [[ 94  97 103]
  [100 104  93]
  [108  78  98]]]


In [6]:
print(arr1/2)
print(arr1 ** 2)

[[[ -4.   -3.5  -4. ]
  [-11.5   4.   -4.5]
  [-10.5  -2.5  -1. ]]

 [[ -5.5   6.    7. ]
  [  3.    5.5   5.5]
  [  0.   -7.    1. ]]

 [[ -3.   -1.5   1.5]
  [  0.    2.   -3.5]
  [  4.  -11.   -1. ]]]
[[[ 64  49  64]
  [529  64  81]
  [441  25   4]]

 [[121 144 196]
  [ 36 121 121]
  [  0 196   4]]

 [[ 36   9   9]
  [  0  16  49]
  [ 64 484   4]]]


In [7]:
print(arr1 * arr1)

[[[ 64  49  64]
  [529  64  81]
  [441  25   4]]

 [[121 144 196]
  [ 36 121 121]
  [  0 196   4]]

 [[ 36   9   9]
  [  0  16  49]
  [ 64 484   4]]]


In [9]:
print(arr1 * (arr2/4))

[[[-36.    -7.    -8.  ]
  [ 74.75  30.    15.75]
  [ -0.   -15.    -1.  ]]

 [[ -8.25  15.   -24.5 ]
  [-31.5   27.5    8.25]
  [  0.   -35.    -3.  ]]

 [[  6.    -3.    -6.75]
  [ -0.     0.    -1.75]
  [-12.   -16.5   -2.  ]]]


Broadcasting behavoir

### 

In [12]:
arr3=np.array([[[0,1,0]]])
print(arr3)

[[[0 1 0]]]


In [11]:
print(arr1*arr3)

[[[  0  -7   0]
  [  0   8   0]
  [  0  -5   0]]

 [[  0  12   0]
  [  0  11   0]
  [  0 -14   0]]

 [[  0  -3   0]
  [  0   4   0]
  [  0 -22   0]]]


In [16]:
arr4=arr3.transpose((0,2,1))
print(arr4)

[[[0]
  [1]
  [0]]]


In [17]:
print(arr1 * arr4)

[[[  0   0   0]
  [-23   8  -9]
  [  0   0   0]]

 [[  0   0   0]
  [  6  11  11]
  [  0   0   0]]

 [[  0   0   0]
  [  0   4  -7]
  [  0   0   0]]]


Linear algebra

In [18]:
arr6=np.arange(8)
print(arr6)

[0 1 2 3 4 5 6 7]


In [19]:
print(arr6.reshape(2,4))

[[0 1 2 3]
 [4 5 6 7]]


In [20]:
print(arr6.reshape(2,2,2))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [23]:
from sklearn.datasets import load_iris
iris=load_iris().data[:,:]
print(iris)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [22]:
print(iris.T)

[[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
  5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
  5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
  6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
  6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
  5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
  6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
  6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
  6.7 6.7 6.3 6.5 6.2 5.9]
 [3.5 3.  3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 3.7 3.4 3.  3.  4.  4.4 3.9 3.5
  3.8 3.8 3.4 3.7 3.6 3.3 3.4 3.  3.4 3.5 3.4 3.2 3.1 3.4 4.1 4.2 3.1 3.2
  3.5 3.6 3.  3.4 3.5 2.3 3.2 3.5 3.8 3.  3.8 3.2 3.7 3.3 3.2 3.2 3.1 2.3
  2.8 2.8 3.3 2.4 2.9 2.7 2.  3.  2.2 2.9 2.9 3.1 3.  2.7 2.2 2.5 3.2 2.8
  2.5 2.8 2.9 3.  2.8 3.  2.9 2.6 2.4 2.4 2.7 2.7 3.  3.4 3.1 2.3 3.  2.5
  2.6 3.  2.

In [24]:
iris_cp=iris.copy()
iris_cp

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [27]:
# the last coloumn will be made of its own
y=iris_cp[:,3]
# the rest will be another datasets
x=np.concatenate((np.ones(shape=(iris_cp.shape[0],1)),iris_cp[:,0:3]),axis=1)
print(y)

[0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 0.2 0.2 0.1 0.1 0.2 0.4 0.4 0.3
 0.3 0.3 0.2 0.4 0.2 0.5 0.2 0.2 0.4 0.2 0.2 0.2 0.2 0.4 0.1 0.2 0.2 0.2
 0.2 0.1 0.2 0.2 0.3 0.3 0.2 0.6 0.4 0.3 0.2 0.2 0.2 0.2 1.4 1.5 1.5 1.3
 1.5 1.3 1.6 1.  1.3 1.4 1.  1.5 1.  1.4 1.3 1.4 1.5 1.  1.5 1.1 1.8 1.3
 1.5 1.2 1.3 1.4 1.4 1.7 1.5 1.  1.1 1.  1.2 1.6 1.5 1.6 1.5 1.3 1.3 1.3
 1.2 1.4 1.2 1.  1.3 1.2 1.3 1.3 1.1 1.3 2.5 1.9 2.1 1.8 2.2 2.1 1.7 1.8
 1.8 2.5 2.  1.9 2.1 2.  2.4 2.3 1.8 2.2 2.3 1.5 2.3 2.  2.  1.8 2.1 1.8
 1.8 1.8 2.1 1.6 1.9 2.  2.2 1.5 1.4 2.3 2.4 1.8 1.8 2.1 2.4 2.3 1.9 2.3
 2.5 2.3 1.9 2.  2.3 1.8]


In [28]:
print(x)

[[1.  5.1 3.5 1.4]
 [1.  4.9 3.  1.4]
 [1.  4.7 3.2 1.3]
 [1.  4.6 3.1 1.5]
 [1.  5.  3.6 1.4]
 [1.  5.4 3.9 1.7]
 [1.  4.6 3.4 1.4]
 [1.  5.  3.4 1.5]
 [1.  4.4 2.9 1.4]
 [1.  4.9 3.1 1.5]
 [1.  5.4 3.7 1.5]
 [1.  4.8 3.4 1.6]
 [1.  4.8 3.  1.4]
 [1.  4.3 3.  1.1]
 [1.  5.8 4.  1.2]
 [1.  5.7 4.4 1.5]
 [1.  5.4 3.9 1.3]
 [1.  5.1 3.5 1.4]
 [1.  5.7 3.8 1.7]
 [1.  5.1 3.8 1.5]
 [1.  5.4 3.4 1.7]
 [1.  5.1 3.7 1.5]
 [1.  4.6 3.6 1. ]
 [1.  5.1 3.3 1.7]
 [1.  4.8 3.4 1.9]
 [1.  5.  3.  1.6]
 [1.  5.  3.4 1.6]
 [1.  5.2 3.5 1.5]
 [1.  5.2 3.4 1.4]
 [1.  4.7 3.2 1.6]
 [1.  4.8 3.1 1.6]
 [1.  5.4 3.4 1.5]
 [1.  5.2 4.1 1.5]
 [1.  5.5 4.2 1.4]
 [1.  4.9 3.1 1.5]
 [1.  5.  3.2 1.2]
 [1.  5.5 3.5 1.3]
 [1.  4.9 3.6 1.4]
 [1.  4.4 3.  1.3]
 [1.  5.1 3.4 1.5]
 [1.  5.  3.5 1.3]
 [1.  4.5 2.3 1.3]
 [1.  4.4 3.2 1.3]
 [1.  5.  3.5 1.6]
 [1.  5.1 3.8 1.9]
 [1.  4.8 3.  1.4]
 [1.  5.1 3.8 1.6]
 [1.  4.6 3.2 1.4]
 [1.  5.3 3.7 1.5]
 [1.  5.  3.3 1.4]
 [1.  7.  3.2 4.7]
 [1.  6.4 3.2 4.5]
 [1.  6.9 3.

In [29]:
# matrix product
X_sq=X.T.dot(X)
print(X_sq)

NameError: name 'X' is not defined