# Creating Numpy Arrays

In [1]:
import numpy as np

In [3]:
vec1=np.ones(5)
print(vec1)

[1. 1. 1. 1. 1.]


In [4]:
vec1.dtype

dtype('float64')

In [6]:
vec1.dtype=np.int8
print(vec1)
vec1.dtype

[  0   0   0   0   0   0 -16  63   0   0   0   0   0   0 -16  63   0   0
   0   0   0   0 -16  63   0   0   0   0   0   0 -16  63   0   0   0   0
   0   0 -16  63]


dtype('int8')

In [9]:
vec1=np.ones(5)
vec1=np.array(vec1,dtype=np.int8)
print(vec1)
vec1.dtype

[1 1 1 1 1]


dtype('int8')

Lets make cubes of zeroes 

In [11]:
arr1=np.zeros((2,2,2),dtype=np.float64)
print(arr1)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


Lets make 3*3 matrix filled with randon values

In [12]:
mat1=np.random.randn(3,3)
print(mat1)

[[-0.81562306  0.93390049  0.43156132]
 [ 0.16845701 -0.21395597  0.60587634]
 [-0.17978881  0.10229181 -1.05061864]]


In [13]:
mat2=np.array([["pankaj","ram"],["rohan","rajan"]])
mat2

array([['pankaj', 'ram'],
       ['rohan', 'rajan']], dtype='<U6')

In [14]:
arr2=np.array([[(1,2,3),(4,3,6)],[(1,np.nan,1),(2,2,2)]])
arr2

array([[[ 1.,  2.,  3.],
        [ 4.,  3.,  6.]],

       [[ 1., nan,  1.],
        [ 2.,  2.,  2.]]])

In [15]:
mat2_cpy=mat2

In [16]:
print(mat2_cpy)

[['pankaj' 'ram']
 ['rohan' 'rajan']]


In [18]:
mat2[0,0]="liam"
print(mat2)
print(mat2_cpy)

[['liam' 'ram']
 ['rohan' 'rajan']]
[['liam' 'ram']
 ['rohan' 'rajan']]


In [19]:
mat2_cpy=mat2.copy()
mat2[0,0]="amy"
print(mat2)
print(mat2_cpy)

[['amy' 'ram']
 ['rohan' 'rajan']]
[['liam' 'ram']
 ['rohan' 'rajan']]


Lets save the file with some arrays , first we all check current working dir


In [20]:
%pwd


'C:\\jupyter-python-code'

Lets save into .npy file

In [21]:
# change directory use %cd
np.save("arr1",arr1)

this is a binary file now in our working directory , you can load this file

In [22]:
new_arr1=np.load("arr1.npy")
print(new_arr1)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


Lets create csv file thats hold the information in  mat1

In [23]:
np.savetxt("mat1.csv",mat1,delimiter=',')

Lets read the content inside mat1.csv

In [25]:
matfile=open("mat1.csv",'r')
for i in matfile:
    print(i)

-8.156230553970539310e-01,9.339004884113218941e-01,4.315613211386921666e-01

1.684570083739296842e-01,-2.139559689793480990e-01,6.058763358539284161e-01

-1.797888082919531505e-01,1.022918051935040457e-01,-1.050618644102035093e+00



In [26]:
matfile.close()

In [27]:
mat_new=np.loadtxt("mat1.csv",delimiter=',')
print(mat_new)

[[-0.81562306  0.93390049  0.43156132]
 [ 0.16845701 -0.21395597  0.60587634]
 [-0.17978881  0.10229181 -1.05061864]]
