# Broadcasting in Numpy

In [1]:
import numpy as np

In [7]:
#when two matrix we are add or sub

x=np.ones((4,4))
y=np.ones((4,4))
add_row=x+y
add_row

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [18]:
# when order is not same
x=np.ones((4,3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
y=np.array([1,2,3])
print(y)

[1 2 3]


In [20]:
# add each row of x using broadcast
add_row=x+y

In [21]:
add_row

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [24]:
z=np.array([10])

In [25]:
z


array([10])

In [26]:
add_row=x+z

In [27]:
add_row

array([[11., 11., 11.],
       [11., 11., 11.],
       [11., 11., 11.],
       [11., 11., 11.]])

In [28]:
# create an ndarray of 4*1 to braodcast across column

sample=np.array([[1,2,3,4]])
sample

array([[1, 2, 3, 4]])

In [30]:
x=np.ones((4,4))
transpose=sample.T
print(transpose)

[[1]
 [2]
 [3]
 [4]]


In [31]:
# add to each column of x using broadcast
add_column=x+transpose
add_column

array([[2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [32]:
# create scalar array,which will broadcastinboth
add_scalar=np.array([1])
print(x+add_scalar)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
