# Slicing Array

In [2]:
import numpy as np
my_vector=np.array([-17,-4,0,2,21,32])

In [3]:
my_vector


array([-17,  -4,   0,   2,  21,  32])

In [4]:
my_vector[0]

-17

In [5]:
my_vector[-3]

2

In [6]:
my_vector[22]

IndexError: index 22 is out of bounds for axis 0 with size 6

In [7]:
305%7

4

In [8]:
my_vector[305%7]

21

In [9]:
my_vector.size

6

In [10]:
my_vector[305%my_vector.size]

32

In [11]:
my_array=np.arange(35)

In [12]:
my_array.shape=(7,5)

In [13]:
my_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [16]:
my_array[2:5]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
my_array[-2]

array([25, 26, 27, 28, 29])

In [18]:
my_array[2,4]

14

In [19]:
my_array[2][4]

14

In [20]:
row=2
column=4
my_array[row,column]

14

In [21]:
my_three_dimensinal=np.arange(70)
my_three_dimensinal.shape=(2,7,5)
my_three_dimensinal

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [22]:
my_three_dimensinal[1]

array([[35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69]])

In [23]:
my_three_dimensinal[1,3]

array([50, 51, 52, 53, 54])

my_three_dimensinal[1,3,2]=1111

In [26]:
my_three_dimensinal

array([[[   0,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9],
        [  10,   11,   12,   13,   14],
        [  15,   16,   17,   18,   19],
        [  20,   21,   22,   23,   24],
        [  25,   26,   27,   28,   29],
        [  30,   31,   32,   33,   34]],

       [[  35,   36,   37,   38,   39],
        [  40,   41,   42,   43,   44],
        [  45,   46,   47,   48,   49],
        [  50,   51, 1111,   53,   54],
        [  55,   56,   57,   58,   59],
        [  60,   61,   62,   63,   64],
        [  65,   66,   67,   68,   69]]])

# boolean mask Arrays

In [3]:
import numpy as np
my_vector=np.array([-17,-4,0,2,21,37])
my_vector

array([-17,  -4,   0,   2,  21,  37])

In [4]:
zero_mod_7_mask=0==(my_vector%7)

In [5]:
zero_mod_7_mask

array([False, False,  True, False,  True, False])