In [1]:
import numpy as np

In [2]:
int_ones=np.ones((2,2),dtype=np.uint8)
int_ones

array([[1, 1],
       [1, 1]], dtype=uint8)

In [3]:
float_ones=np.ones((2,2),dtype=np.float16)
float_ones

array([[1., 1.],
       [1., 1.]], dtype=float16)

In [5]:
string_arr=np.array(["pankaj","trushan","rithvik"])
string_arr

array(['pankaj', 'trushan', 'rithvik'], dtype='<U7')

In [8]:
string_arr[1]="rajveersingh"
string_arr

array(['pankaj', 'rajveer', 'rithvik'], dtype='<U7')

In [10]:
string_arr=np.array(["ram","ragini","rohan"],dtype='<U16')
string_arr

array(['ram', 'ragini', 'rohan'], dtype='<U16')

In [11]:
string_arr[1]="nehasinghpandey"

In [12]:
string_arr

array(['ram', 'nehasinghpandey', 'rohan'], dtype='<U16')

# Special Values

now lets generating special values like nan or inf

In [15]:
vec1=np.array([1,-1,0],dtype=np.float16)
vec1
vec2=vec1/0
vec2

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Anaconda\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([ inf, -inf,  nan], dtype=float16)

In [30]:
# Can we detect special value
for i in vec2:
    print(i)
    print("--------")
    print('inf: '+ str(i==np.inf))
    print('-inf :'+ str(i==-np.inf))
    print('NaN : '+ str(i==np.nan)) #doesnt work
    print('\n\n')

inf
--------
inf: True
-inf :False
NaN : False



-inf
--------
inf: False
-inf :True
NaN : False



nan
--------
inf: False
-inf :False
NaN : False





In [29]:
# better way
for i in vec2:
    print(i)
    print("--------")
    print('inf: '+ str(i==np.inf))
    print('-inf :'+ str(i==-np.inf))
    print('NaN : '+ str(np.isnan(i))) # does work
    print('\n\n')

inf
--------
inf: True
-inf :False
NaN : False



-inf
--------
inf: False
-inf :True
NaN : False



nan
--------
inf: False
-inf :False
NaN : True





In [37]:
# finite vs infinte
for i in vec2:
    print(i)
    print("--------")
    print('is finte ?'+ str(np.isfinite(i)))
    print('is infinite ?'+ str(np.isinf(i)))

    print('\n\n')

inf
--------
is finte ?False
is infinite ?True



-inf
--------
is finte ?False
is infinite ?True



nan
--------
is finte ?False
is infinite ?False





In [39]:
vec2[0]+1

inf

In [40]:
vec2[0]* -1

-inf

In [41]:
vec2[2]+1

nan

In [42]:
2 ** vec2[0]

inf

In [43]:
np.inf-np.inf

nan

In [46]:
vec3=np.array([999],dtype=np.float64)
vec3

array([999.])

In [47]:
vec3[0] ** vec3[0]

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: overflow encountered in double_scalars
  """Entry point for launching an IPython kernel.


inf

In [49]:
vec4=np.ones(5)
vec4[0]=np.nan
vec4

array([nan,  1.,  1.,  1.,  1.])

In [50]:
np.sum(vec4)

nan

In [52]:
np.nansum(vec4) #igonores nan

4.0