# Statistical operation
1. mean
2. median
3. sum

In [2]:
import numpy as np
# create matrices of 4*3
example=np.array([[12,13,14],[13,56,78],[67,34,23],[13,12,10]])
print(example)

[[12 13 14]
 [13 56 78]
 [67 34 23]
 [13 12 10]]


In [3]:
# mean of all elements
print(example.mean())


28.75


In [4]:
#find the mean of each row

print(example.mean(axis=1))

[13.         49.         41.33333333 11.66666667]


In [5]:
#find the mean of each column

print(example.mean(axis=0))

[26.25 28.75 31.25]


In [6]:
# find sum
print(example.sum())

345


In [7]:
print(example.sum(axis=1))
print(example.sum(axis=0))

[ 39 147 124  35]
[105 115 125]


In [8]:
#find median
print(np.median(example ,axis=1))
print(np.median(example ,axis=0))

[13. 56. 34. 12.]
[13.  23.5 18.5]


In [9]:
# Compute the x and y coordinates for points on a sine curve 
x = np.arange(0, 3 * np.pi, 0.1) 
y = np.sin(x) 
plt.title("sine wave form") 

# Plot the points using matplotlib 
plt.plot(x, y) 
plt.show() 

NameError: name 'plt' is not defined