# Numpy

NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays.

https://docs.scipy.org/doc/numpy/user/index.html

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.16.2


In [6]:
my_list=[-17,2,34,0,7]
my_list

[-17, 2, 34, 0, 7]

In [4]:
my_array_from_list=np.array(my_list)

In [5]:
my_array_from_list


array([-17,   2,  34,   0,   7])

In [8]:
np.array([2,3,4,12])

array([ 2,  3,  4, 12])

In [9]:
my_array_from_list*10


array([-170,   20,  340,    0,   70])

In [12]:
my_tuple=(14,-3.543,5+4j,3)
my_array_from_tuple=np.array(my_tuple)

In [13]:
my_array_from_tuple

array([14.   +0.j, -3.543+0.j,  5.   +4.j,  3.   +0.j])

In [16]:
my_ndarray=np.array([3,4,2,6],dtype=float)

In [17]:
my_ndarray

array([3., 4., 2., 6.])

In [18]:
my_tuple*6

(14,
 -3.543,
 (5+4j),
 3,
 14,
 -3.543,
 (5+4j),
 3,
 14,
 -3.543,
 (5+4j),
 3,
 14,
 -3.543,
 (5+4j),
 3,
 14,
 -3.543,
 (5+4j),
 3,
 14,
 -3.543,
 (5+4j),
 3)

In [20]:
np.array(my_tuple)*6

array([ 84.    +0.j, -21.258 +0.j,  30.   +24.j,  18.    +0.j])

# Intrinsic numpy array  creation using numpy method

# arange(7)

In [22]:
arange(7)

NameError: name 'arange' is not defined

In [23]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [24]:
np.arange(10,23)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [25]:
np.arange(10,23)-10+1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [26]:
len(np.arange(10,23))

13

In [27]:
my_range_array=np.arange(10,23)

In [28]:
my_range_array.size

13

In [30]:
np.arange(10,26,5)

array([10, 15, 20, 25])

In [31]:
np.arange(26,step=5)

array([ 0,  5, 10, 15, 20, 25])

# linspace
Evenly spaced numbers with careful handling of endpoints.

In [35]:
np.linspace(5,15,4)

array([ 5.        ,  8.33333333, 11.66666667, 15.        ])

# Zeros
Return a new array of given shape and type, filled with zeros

In [36]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [37]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

# Ones 
Return a new array of given shape and type, filled with ones.

In [38]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [39]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
np.zeros((5,6,3),dtype='int')

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [43]:
np.zeros(11,dtype='int64')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)