In [1]:
import numpy as np

# without additional parameter

a=np.array([1,2,3,6])
print(type(a))
print(a)

<type 'numpy.ndarray'>
[1 2 3 6]


In [3]:
print(a[0])
print(a[3])

1
6


In [4]:
# more than one dimensions 
import numpy as np 
a = np.array([[1, 2], [3, 4]]) 
print a

[[1 2]
 [3 4]]


In [5]:
# minimum dimensions 
import numpy as np 
a = np.array([1, 2, 3,4,5], ndmin = 2) 
print a

[[1 2 3 4 5]]


In [9]:
# dtype parameter 
import numpy as np 
a = np.array([1, 2, 3], dtype = float) 
print a

[1. 2. 3.]


In [10]:
# using array-scalar type 
import numpy as np 
dt = np.dtype(np.int32) 
print dt

int32


In [11]:
#int8, int16, int32, int64 can be replaced by equivalent string 'i1', 'i2','i4', etc. 
import numpy as np 

dt = np.dtype('i4')
print dt 

int32


In [12]:
# first create structured data type 
import numpy as np 
dt = np.dtype([('age',np.int8)]) 
print dt 

[('age', 'i1')]


In [14]:
# now apply it to ndarray object 
import numpy as np 

dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print a
print (type(dt))

[(10,) (20,) (30,)]
<type 'numpy.dtype'>


In [15]:
# file name can be used to access content of age column 
import numpy as np 

dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print a['age']

[10 20 30]


In [24]:
#shape
import numpy as np 
a = np.array([[1,2,3,7], [4,5,6,7]]) 
print a.shape

(2L, 4L)


In [25]:
# this resizes the ndarray 
import numpy as np 

a = np.array([[1,2,3],[4,5,6]]) 
a.shape = (3,2) 
print a 

[[1 2]
 [3 4]
 [5 6]]


In [34]:
# an array of evenly spaced numbers 
import numpy as np 
a = np.arange(5,100) 
print a

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52
 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76
 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [40]:
# this is one dimensional array 
import numpy as np 
a = np.arange(100) 
a.ndim  

# now reshape it 
b = a.reshape(4,5,5) 
print b 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]

 [[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]]

 [[75 76 77 78 79]
  [80 81 82 83 84]
  [85 86 87 88 89]
  [90 91 92 93 94]
  [95 96 97 98 99]]]


import numpy as np 
x = np.empty([3,2], dtype = int) 
print x

In [43]:
import numpy as np 
x = np.empty([3,2], dtype = int) 
print x

[[1 2]
 [3 4]
 [5 6]]


In [42]:
import numpy as np 
x = np.empty([3,2], dtype = int,order='F') 
print x

[[         0 1073741824]
 [1072693248          0]
 [         0 1074266112]]


In [44]:
# array of five zeros. Default dtype is float 
import numpy as np 
x = np.zeros(5) 
print x

[0. 0. 0. 0. 0.]


In [49]:
import numpy as np 
x = np.zeros((5,2), dtype = np.int) 
print x

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [50]:
# custom type 
import numpy as np 
x = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])  
print x

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


In [53]:
import numpy as np 
x = np.linspace(10,20,5) 
print x

[10.  12.5 15.  17.5 20. ]
